dataset_configs:
  train:
    sequences_path: ./datasets/spikeprot_train.txt
    immunogenicity_scores_path: ./datasets/train_scores.npy
  val:
    sequences_path: ./datasets/spikeprot_valid.txt
    immunogenicity_scores_path: ./datasets/valid_scores.npy
  test:
    sequences_path: ./datasets/spikeprot_test.txt
    immunogenicity_scores_path: ./datasets/test_scores.npy
model_configs:
  model_type: lstm
  hyperparameters:
    max_seq_len: 1299
    hidden_dim: 128
    num_layers: 2
    embedding_dim: 128
    regularizers: []
    dropout: 0.05
    batch_size: 256
    optimizer: "adam"
    learning_rate: 1e-4
    grad_accumulation_step: 1
training_configs:
  generator_pretrain_epochs: 100
  epochs: 150
  eval_steps: 1
  device: 0
  random_seed: 1234
  outputs_dir: "train_outputs"