dataset_configs:
  train:
    sequences_path: ./datasets/train
  val:
    sequences_path: ./datasets/valid
  test:
    sequences_path: ./datasets/test
model_configs:
  model_type: rnaformer
  hyperparameters:
    max_seq_len: 3813
    hidden_dim: 128
    nhead: 4
    num_layers: 2
    regularizers: []
    dropout: 0.5
    batch_size: 32
    optimizer: "adam"
    learning_rate: 1e-4
    grad_accumulation_step: 1
    immunogenicity_as_value: False
training_configs:
  epochs: 100
  eval_steps: 1
  checkpoint_steps: 10
  device: 0
  random_seed: 1234
  outputs_dir: "train_outputs"